volumes:
  db-data:
#  prometheus-data:
#  grafana-data:


services:
  proxy:
    image: traefik:latest
    container_name: proxy
    ports:
      - "443:443"
      - "1433:1433"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - ./proxy/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - RABBIT_HOST=$RABBIT_HOST
      - RABBIT_USER=$RABBIT_USER
      - RABBIT_PASSWORD=$RABBIT_PASSWORD
      - AUTH_HOST=$AUTH_HOST
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=$ASPNETCORE_HTTP_PORTS
    labels:
      - "prometheus-job=api-gateway"
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api-gateway.entrypoints=websecure"
    depends_on:
      - auth-api
      - parcel-api
      - rabbit-mq
  
  auth-api:
    image: auth-api
    container_name: $AUTH_HOST
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    environment:
      - RABBIT_HOST=$RABBIT_HOST
      - RABBIT_USER=$RABBIT_USER
      - RABBIT_PASSWORD=$RABBIT_PASSWORD
      - AUTH_HOST=$AUTH_HOST
      - DB_HOST=$DB_HOST
      - DATABASE=AuthApi
      - DB_PASSWORD=$DB_PASSWORD
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=$ASPNETCORE_HTTP_PORTS
    labels:
      - "prometheus-job=auth-api"
    depends_on:
      - sql-server
      - rabbit-mq
  
  parcel-api:
    image: parcel-api
    container_name: parcel-api
    build:
      context: .
      dockerfile: ParcelApi/Dockerfile
    environment:
      - RABBIT_HOST=$RABBIT_HOST
      - RABBIT_USER=$RABBIT_USER
      - RABBIT_PASSWORD=$RABBIT_PASSWORD
      - DB_HOST=$DB_HOST
      - DATABASE=ParcelApi
      - DB_PASSWORD=$DB_PASSWORD
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_HTTP_PORTS=$ASPNETCORE_HTTP_PORTS
    labels:
      - "prometheus-job=parcel-api"
    depends_on:
      - sql-server
      - rabbit-mq
  
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: $DB_HOST
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$DB_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.loop-sql-db.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.loop-sql-db.entrypoints=database"
    volumes:
      - db-data:/var/opt/mssql

  rabbit-mq:
    image: masstransit/rabbitmq:latest
    container_name: $RABBIT_HOST
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBIT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBIT_PASSWORD
